source "https://api.berkshelf.com"

cookbook 'mysql', '~> 8.2.0'
cookbook 'locale', '~> 2.0.0'
cookbook 'apache2', '~> 3.2.2'
cookbook 'nodejs', '~> 3.0.0'
cookbook 'sudo', '~> 3.3.1'
cookbook 'get-native.com-cookbook', git: 'git@home.github.com:hank-ehly/get-native.com-cookbook.git'
cookbook 'build-essential', '~> 8.0.0'
cookbook 'deploy_key', '~> 0.3.0'
cookbook 'apt', '~> 6.0.1'
cookbook 'openssh', '~> 2.1.1'
cookbook 'acme', '~> 2.0.0'
