source 'https://rubygems.org'

gem 'chef', '~> 12.15', '>= 12.15.19'
gem 'test-kitchen', '~> 1.13', '>= 1.13.2'
gem 'kitchen-vagrant', '~> 0.20.0'
gem 'berkshelf', '~> 5.1'
gem 'knife-solo', '~> 0.6.0'
