site_name: Get Native
pages:
- Home: index.md
- POST /account/update_profile_image: post_account_update_profile_image.md
- GET /cued_videos/list: get_cued_videos_list.md
- DELETE /users/authenticate: delete_users_authenticate.md
- GET /speakers/show: get_speakers_show.md
- GET /users/show: get_users_show.md
- GET /videos: get_videos.md
- GET /videos/search: get_videos_search.md
- GET /videos/show/:id: get_videos_show_id.md
theme: readthedocs
