site_name: Get Native
pages:
- Home: index.md
- 1. Purpose & Goal: purpose_and_goal.md
- 2. Features: features.md
- 3. Database Schema: database_schema.md
- 4. Architecture: architecture.md
- 5. API: api.md
- 6. Screens: screens.md
theme: readthedocs
