site_name: Get Native
pages:
- Home: index.md
- 1. Purpose & Goal: pages/01_purpose_and_goal.md
- 2. Features: pages/02_features.md
- 3. Database Schema: pages/03_database_schema.md
- 4. Architecture: pages/04_architecture.md
- 5. API: pages/05_api.md
- 6. Screens: pages/06_screens.md
- 7. Saving & Displaying Collocations: pages/07_collocations.md
theme: readthedocs
