/**
 * endpoint
 * getnativelearning.com
 *
 * Created by henryehly on 2017/01/29.
 */

export enum APIHandle {
    CREATE_SESSION,
    DELETE_USER,
    VIDEO,
    VIDEOS,
    LIKE_VIDEO,
    UNLIKE_VIDEO,
    STUDY_STATS,
    WRITING_ANSWERS,
    CATEGORIES,
    UPDATE_USER,
    EDIT_PASSWORD,
    EDIT_EMAIL,
    CREATE_USER,
    CONFIRM_EMAIL,
    CONFIRM_EMAIL_UPDATE,
    RESEND_CONFIRMATION_EMAIL,
    QUEUE_VIDEO,
    DEQUEUE_VIDEO,
    START_STUDY_SESSION,
    COMPLETE_STUDY_SESSION,
    WRITING_QUESTIONS,
    CREATE_WRITING_ANSWER,
    ME,
    SEND_PASSWORD_RESET_LINK,
    RESET_PASSWORD,
    DELETE_PROFILE_IMAGE,
    UPLOAD_PROFILE_IMAGE
}
