version: 2
jobs:
  build:
    working_directory: ~/getnativelearning.com

    docker:
      - image: circleci/ruby:2.3
        environment:
          NODE_VERSION: '8.4.0'

    steps:
      - checkout

      - run:
          name: Install nvm
          command: .circleci/nvm.sh ${NODE_VERSION}

      - run: echo 'export PATH=${HOME}/.nvm/versions/node/v${NODE_VERSION}/bin:$PATH' >> $BASH_ENV

      - restore_cache:
          keys:
              - api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install Node Dependencies
          command: |
              node --version
              npm --version
              npm install

      - save_cache:
          key: api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: xvfb-run -a npm run lint -- --type-check

      - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox

      - deploy:
          name: Deploy
          command: .circleci/deploy.sh ${CIRCLE_BRANCH}
