/**
 * endpoint
 * get-native.com
 *
 * Created by henryehly on 2017/01/29.
 */

export enum APIHandle {
    LOGIN,
    VIDEO,
    VIDEOS,
    LIKE_VIDEO,
    UNLIKE_VIDEO,
    STUDY_STATS,
    WRITING_ANSWERS,
    CATEGORIES,
    EDIT_ACCOUNT,
    EDIT_PASSWORD,
    EDIT_EMAIL,
    ACCOUNT,
    REGISTER,
    CONFIRM_EMAIL,
    RESEND_CONFIRMATION_EMAIL,
    QUEUE_VIDEO,
    DEQUEUE_VIDEO,
    START_STUDY_SESSION,
    COMPLETE_STUDY_SESSION,
    WRITING_QUESTIONS,
    CREATE_WRITING_ANSWER
}
