name 'get-native.com'
maintainer 'Hank Ehly'
maintainer_email 'henry.ehly@gmail.com'
license 'all_rights'
description 'Configures get-native.com'
long_description 'Configures get-native.com'
version '0.1.0'

depends 'mysql', '~> 8.0.4'
depends 'locale', '~> 2.0.0'
depends 'apache2', '~> 3.2.2'
depends 'nodejs', '~> 2.4.4'
depends 'sudo', '~> 3.0.0'
depends 'build-essential', '~> 7.0.1'
